curl -X POST http://localhost:3000/api/project \
  -H "Content-Type: application/json" \
  -d '{
    "name": "DePINScan Blogs",
    "ghost_api_key": "0e7c6d898338044caa7769b3c8",
    "ghost_domain": "https://blog.depinscan.io",
    "locales": ["en", "zh"],
    "rule": "DePINScan is a blockchain-based platform that provides a comprehensive overview of the DePIN ecosystem."
  }'

### 
# get all projects
curl -X GET http://localhost:3000/api/project \
  -H "Content-Type: application/json" \
  -d '{
    "name": "Test Project",
    "ghost_api_key": "your-ghost-api-key",
    "ghost_domain": "your-ghost-domain",
    "locales": ["en", "zh"],
    "rule": "Translate the following text into multiple languages"
  }'